---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-server
  template: 
    metadata:
      labels:
        app: grafana-server
    spec:
      containers:
        - name: grafana-server
          image: grafana/grafana
          resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 200m
              memory: 300Mi
          ports:
            - containerPort: 3000