---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer-server
  template: 
    metadata:
      labels:
        app: writer-server
    spec:
      containers:
        - name: writer-server
          image: writerdockerise
          imagePullPolicy: IfNotPresent
          # ports:
          #   - containerPort: 5555