---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-master
  labels:
    run: mariadb-master
spec:
  ports:
    - protocol: "TCP" 
      port: 3306
      targetPort: 3306
  type: ClusterIP
  selector:
    app: mariadb-master