---
apiVersion: v1
kind: Service
metadata:
  name: grafana-server
  labels:
    run: grafana-server
spec:
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  type: ClusterIP
  selector:
    app: grafana-server