---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway-server
  labels:
    run: pushgateway-server
spec:
  ports:
    - protocol: "TCP"
      port: 9091
      targetPort: 9091
  type: ClusterIP
  selector:
    app: pushgateway-server