---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-slave
  labels:
    run: mariadb-slave
spec:
  ports:
    - protocol: "TCP"
      port: 3306
      targetPort: 3306
  type: ClusterIP
  selector:
    app: mariadb-slave